  
name: "Imperial"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: r-lib/actions/setup-r@v1
    - name: Install R dependencies
      run: Rscript -e 'install.packages(c("matrixStats", "tibble", "tidyverse", "MMWRweek", "lubridate"))' 

    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install python requirenments
      run: |
        pip3 install -r github-actions/Imperial_req.txt
         
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Weekly Forecasts" 
      
    - name: Process Imperial
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        # Execute Scripts
        git checkout Imperial_actions
        python3 code/auto_download/auto-download-imperial.py
        cd ./data-raw/Imperial
        Rscript Imperial-processing-script.R
        cd ../../
        
        # Push to Github
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git add --all
        git commit -m "Weekly Imperial forecasts"
        git push --quiet --set-upstream origin HEAD:Imperial_actions
        echo "pushed to github"
        
        #create PR
        cd ./code/auto_download
        python3 create_PR.py "Weekly Imperial forecasts" "Imperial_actions"
        cd ../../
        
        
